version: "3.7"

services:
  influxdb:
    image: influxdb:1.7-alpine
    hostname: influxdb
  chronograf:
    image: chronograf:1.7-alpine
    hostname: chronograf
    environment:
      INFLUXDB_URL: "http://influxdb:8086"
      KAPACITOR_URL: "http://kapacitor:9092"
    ports:
      - 8888:8888
  kapacitor:
    image: kapacitor:1.5-alpine
    hostname: kapacitor
    environment:
      KAPACITOR_INFLUXDB_0_URLS_0: "http://influxdb:8086"
      KAPACITOR_LOAD_ENABLED: "true"
      KAPACITOR_LOAD_DIR: "/etc/kapacitor/load"
    volumes:
      - type: bind
        source: ./kapacitor/custom
        target: /etc/kapacitor/customizations/demo/
      - type: bind
        source: ./kapacitor/load
        target: /etc/kapacitor/load
    ports:
      - 9092:9092
    links:
      - influxdb